#!/usr/bin/env node
/* eslint-env node */
/*
 * Copies the Unity Android export (AR_MODE/Builds/android/unityLibrary) into
 * Mobile/unity/builds/android/unityLibrary, the location @azesmway/react-native-unity's Expo plugin
 * points settings.gradle at (Mobile/android is generated by `expo prebuild`, so it cannot hold the library).
 * Safe to re-run: the destination is replaced.
 *
 *   node scripts/sync-unity.js [path/to/export/android]
 */
const fs = require('fs');
const path = require('path');

const mobile = path.resolve(__dirname, '..');
const exportDir = path.resolve(process.argv[2] || path.join(mobile, '..', 'AR_MODE', 'Builds', 'android'));
const src = path.join(exportDir, 'unityLibrary');
const dest = path.join(mobile, 'unity', 'builds', 'android', 'unityLibrary');

if (!fs.existsSync(path.join(src, 'build.gradle'))) {
  console.error(`No unityLibrary found at ${src}\nExport from Unity first (PhyXara > Export Android, or see Mobile/src/unity/README.md).`);
  process.exit(1);
}

fs.rmSync(dest, { recursive: true, force: true });
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.cpSync(src, dest, { recursive: true });

// The library docs: drop the launcher <intent-filter> from the library manifest, the RN app is the only launcher.
const manifest = path.join(dest, 'src', 'main', 'AndroidManifest.xml');
if (fs.existsSync(manifest)) {
  const xml = fs.readFileSync(manifest, 'utf8');
  const stripped = xml.replace(/<intent-filter>[\s\S]*?<\/intent-filter>/g, '');
  if (stripped !== xml) fs.writeFileSync(manifest, stripped);
}

// Exports that reference ../shared (keepUnitySymbols etc.) need it next to unityLibrary.
const shared = path.join(exportDir, 'shared');
if (fs.existsSync(shared)) {
  fs.cpSync(shared, path.join(path.dirname(dest), 'shared'), { recursive: true });
}

console.log(`Synced ${src}\n    -> ${dest}\nNext: npx expo prebuild --platform android --clean && cd android && gradlew assembleDebug`);
